apiVersion: v1
kind: Pod
metadata:
  labels:
    test: healthcheck
  name: healthcheck
spec:
  restartPolicy: OnFailure
  containers:
    - image:  busybox
      name:  healthcheck
      args: 
      - /bin/sh
      - -c
      - sleep 10; exit 1