apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: httpd2
  namespace: kube-public
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: httpd2
    spec:
      containers:
      - name: httpd2
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name:  httpd2-svc
  namespace: kube-public
spec:
  selector:
    run:  httpd2
  ports:
  - protocol: TCP
    port:  8080
    targetPort:  80