apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: httpd
        editor: vscode
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80