apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness
spec:
  restartPolicy: OnFailure
  containers:
    - image:  busybox
      name:  liveness
      args: 
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 390; rm -rf /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy;
        initialDelaySeconds: 10
        periodSeconds: 5