apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: myapplication
data:
  PUBLIC_MYSQL_URL_INNODEALING: jdbc:mysql://192.168.8.190:3306
  PUBLIC_MYSQL_USER_INNODEALING: root
  PUBLIC_MYSQL_PASSWD_INNODEALING: test123
