apiVersion: v1
kind: ConfigMap
metadata:
  name: public-config
  namespace: default
data:
  public.mysql.url: jdbc:mysql://192.168.8.190:3306
  public.mysql.user: root
  public.mysql.password: test123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  log_level: INFO