apiVersion: v1
kind: ConfigMap
metadata:
  name: public-config
  namespace: default
  labels:
    app: myapplication
data:
  PUBLIC_MYSQL_URL_INNODEALING: jdbc:mysql://192.168.8.190:3306
  PUBLIC_MYSQL_USER_INNODEALING: root
  PUBLIC_MYSQL_PASSWD_INNODEALING: test123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  log_level: INFO