apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.2
        ports: 
          - containerPort: 80
          - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name:  nginx-svc
spec:
  selector:
    app: nginx
  type:  NodePort
  ports:
  - name:  http
    protocol: TCP
    port:  80
    nodePort: 30080
  - name: https
    protocol: TCP
    port: 443
    nodePort: 30443