apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        editor: frank
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9