apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness
spec:
  restartPolicy: OnFailure
  containers:
    - image:  busybox
      name:  readiness
      args: 
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 390; rm -rf /tmp/healthy; sleep 600
      readinessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy;
        initialDelaySeconds: 10
        periodSeconds: 5